### PR TITLE
Better way to detect dynamic styles

### PR DESCRIPTION
**Pull request by a-ignatov-parc**

### CODE REVIEW

**Comment by a-ignatov-parc** [comment]
@giuseppeg found another case when dynamic styles were detected as static. Tried to implement a better mechanism to detect them. 

If you have other cases let me know 😉

**Comment by giuseppeg** [comment]
sweet thank you!

**Comment by a-ignatov-parc** [comment]
@giuseppeg can you share plans for the release of this fix?

**Comment by giuseppeg** [comment]
I want to include another fix, I'll try to get it out today or tomorrow

**Comment by a-ignatov-parc** [comment]
No need to rush. Just curious about possible ETA 😉

**Pull request merged**
