### PR TITLE
Add support for expressions within template literals

### LINKED ISSUE #25: Expressions within template literal don't work
I would understand if dynamic properties didn't work, but dynamic values don't seem to be working either. Compiling succeeds, but the pieces with the expression seem to be omitted from the inserted script tag.

```
<div>
	<div id={this.state.calendarId}></div>
	<style jsx>{`
			#${this.state.calendarId} .fc-button.fc-state-default {
				border: 2px solid ${buttonColor};
			}
	`}</style>
</div>
```
image

---

```
const buttonColor = 'red';

return (
	<div>
		<div id="foo"></div>
		<style jsx>{`
			#foo .fc-button.fc-state-default {
				border: 2px solid ${buttonColor};
			}
		`}</style>
	</div>
);
```
image

---

```
<div>
	<div id="foo"></div>
	<style jsx>{`
		#foo .fc-button.fc-state-default {
			border: 2px solid red;
		}
	`}</style>
</div>
```
image

Thank you!

### PR DESCRIPTION
**Pull request by giuseppeg**
Fixes #25

### CODE REVIEW

**Comment by giuseppeg** [comment]
@rauchg ran a [benchmark](https://github.com/zeit/styled-jsx/pull/79) on this branch and it is slightly slower.

```
97.36 ops/sec ±3.30% (567 runs sampled)
```

while without expressions:

```
104 ops/sec ±1.32% (562 runs sampled)
```

**Comment by giuseppeg** [comment]
#### Master

```
155 ops/sec ±1.39% (573 runs sampled)
```

#### PR

Without expressions:

```
143 ops/sec ±1.27% (565 runs sampled)
```

With expressions:

```
140 ops/sec ±1.71% (570 runs sampled)
```

ran on a MacBook Pro 2 GHz Intel Core i7, 8 GB 1600 MHz DDR3

**Comment by sarukuku** [comment]
🎉

**Comment by aga5tya** [comment]
:clap:

**Comment by giuseppeg** [comment]
@rauchg 

```
Running 'styled-jsx Babel transform' from ~/code/styled-jsx/benchmark/babel.js ...
  basic x 123 ops/sec ±6.70% (61 runs sampled)
  with expressions x 93.34 ops/sec ±11.77% (52 runs sampled)

Passed:
  'basic' is etalon
  'with expressions' at 1.32x slower
```
Ran on a MacBook Pro (Mid 2014), 2.6 GHz Intel Core i5, 8 GB 1600 MHz DDR3

**Comment by TuckerWhitehouse** [comment]
Anything we can do to help get this merged?

**Comment by aga5tya** [comment]
Waiting on this :cookie:

**Comment by rauchg** [comment]
@TuckerWhitehouse @aga5tya I'd like to understand why it's 30% slower, seems a bit much?

Also, @giuseppeg, what's the impact on an example that *doesn't use expressions*, before and after this patch?

**Comment by TuckerWhitehouse** [comment]
@rauchg what would be acceptable performance?

I ran the benchmarks locally, and these are my results:

`master`
```
Babel transform x 150 ops/sec ±3.40% (572 runs sampled)
'babel' from ~/Sites/styled-jsx/benchmark/babel.js (passed: 1, failed: 0)
  Passed:
    'Babel transform' is etalon
```

`expressions`
```
Running 'styled-jsx Babel transform' from ~/Sites/styled-jsx/benchmark/babel.js ...
  basic x 144 ops/sec ±4.52% (75 runs sampled)
  with expressions x 140 ops/sec ±3.97% (70 runs sampled)
'styled-jsx Babel transform' from ~/Sites/styled-jsx/benchmark/babel.js (passed: 2, failed: 0)
  Passed:
    'basic' is etalon
    'with expressions' at 1.03x slower
```

**Comment by TuckerWhitehouse** [comment]
Re-ran the benchmarks, and updated `expressions` to use a minimum of 500 samples.

`master`
```
Babel transform x 170 ops/sec ±1.50% (573 runs sampled)
```

`expressions`
```
basic x 168 ops/sec ±1.51% (567 runs sampled)
with expressions x 151 ops/sec ±1.32% (563 runs sampled)
  'with expressions' at 1.11x slower
```

**Comment by TuckerWhitehouse** [comment]
Thanks @rauchg, and nice work @giuseppeg!

**Pull request merged**
