### PR TITLE
Fixed dynamic styles detection

### PR DESCRIPTION
**Pull request by a-ignatov-parc**
Fixed case when dynamic styles with compound props was detected as static

### CODE REVIEW

**Comment by a-ignatov-parc** [comment]
@giuseppeg is there any chance we can get this fix released till Friday? 

Don't want to rollback migration to `styled-jsx` just before release :)

**Comment by giuseppeg** [comment]
@a-ignatov-parc hi sorry, looks good. 

Can you add two more tests:

```jsx
const foo = 'red'
() => <div><style jsx>{`div { color: ${foo} }`}</style></div>
```

and one like the one you added but without the `if`? (without a block)

**Comment by a-ignatov-parc** [comment]
Sure 👍

**Comment by a-ignatov-parc** [comment]
Done. Looks good.

**Comment by giuseppeg** [comment]
thanks man, I'll publish a patch release right away

**Comment by a-ignatov-parc** [comment]
Awesome! Thanks a lot 🎉

**Comment by giuseppeg** [comment]
done

**Pull request merged**
