### PR TITLE
Allow whitespace in expressions inside template literals

### LINKED ISSUE #126: Allow whitespace in expressions inside template literals
As of now expressions like the following won't get replaced because I'm using spaces  inside the curly braces.

```JavaScript
<script jsx>{`
  p {
    color: ${ colors.primary }
  }
`}</script>
```
It has to be written as `${colors.primary}`.

Also note that the README's [demo](https://github.com/zeit/styled-jsx#constants-and-config) is using that style.

I believe this is the corresponding source: https://github.com/zeit/styled-jsx/blob/45ba8542f93d5caee262ead08a584a25767eacd5/src/babel.js#L108.

### PR DESCRIPTION
**Pull request by nikvm**
Fixes #126.

So far I refrained from adding an extra test case and instead extended the already present `expressions` fixture.

### CODE REVIEW

**Comment by giuseppeg** [comment]
@nikvm thank you! Do you think that we should add an extra test for strings that contain characters that need to be escaped?

**Comment by nikvm** [comment]
Do you mean: _need to be escaped for the `RegExp`_?

If so, we already have a fixture testing [`p { ${darken(color) + 2} }`](https://github.com/zeit/styled-jsx/blob/master/test/fixtures/expressions.js#L14) where `(`, `)` and `+` need to be escaped. If that was still leading to bugs with escaping it would mean [`string-escape-regexp`](https://www.npmjs.com/package/escape-string-regexp) (which we use internally for escaping) doesn't properly do it's job and tests/fixes should be implemented over there. :trollface:

I guess returning the question: What would a test like that look like?

**Comment by giuseppeg** [comment]
> If that was still leading to bugs with escaping it would mean string-escape-regexp (which we use internally for escaping) doesn't properly do it's job and tests/fixes should be implemented over there.

fair enough :)

**Comment by giuseppeg** [comment]
thank you man!

**Pull request merged**
