### PR TITLE
Fix expressions for the autoprefixed properties (#115)

### PR DESCRIPTION
**Pull request by fatfisz**
This fixes the issue described in #115.

### CODE REVIEW

**Comment by giuseppeg** [comment]
@fatfisz looks good. Do you have multiple references to `___styledjsxexpression_0___` because of autoprefixing?

**Comment by fatfisz** [comment]
Yup, that's the conclusion I came to. Or is there a possibility of a property being multiplied even if not because of autoprefixing?

**Comment by fatfisz** [comment]
I mean, this only happened for `animation`, `animation-duration`, and not for `width` or even `unknown-property`.

**Comment by giuseppeg** [comment]
Right now I cannot thing of any other case. Thanks for the PR

**Pull request merged**
