### PR TITLE
Fix global selectors transform

### PR DESCRIPTION
**Pull request by nkzawa**

### CODE REVIEW

**Comment by giuseppeg** [comment]
@nkzawa which bug is this branch fixing? Can you reference the issues if we have any?

**Comment by nkzawa** [comment]
I just found this bug, but it seems https://github.com/zeit/styled-jsx/issues/95 is the same.

**Comment by cgood92** [comment]
I pulled this down and tried in in my project - it's fixed a few problems I have had.  

Thanks @nkzawa!  I hope that this get's merged soon.... please! :)

**Comment by cgood92** [comment]
@rauchg: Do we need to do a version bump on this so that I can get this using npm/yarn?  Or publish?  Right now when you pull `npm install` 0.5.1, these changes are not in there...

**Pull request merged**
