### PR TITLE
Update the files field on package.json

### PR DESCRIPTION
**Pull request by nkzawa**
Fixes https://github.com/zeit/styled-jsx/issues/16

### CODE REVIEW

**Comment by leo** [comment]
👍

**Comment by MicheleBertoli** [comment]
awesome, thanks!
can you please push this to `npm`?

**Comment by leo** [comment]
@MicheleBertoli sure!

**Comment by leo** [comment]
@MicheleBertoli Working with 0.0.7?

**Comment by NicolasParada** [comment]
Oh, yeah. Finally xD

**Comment by MicheleBertoli** [comment]
yes @leo, thanks!
I just added it to https://github.com/MicheleBertoli/css-in-js

**Comment by leo** [comment]
@MicheleBertoli Nice! But we actually [support](https://github.com/zeit/styled-jsx#server-side-rendering) extracting the CSS file.

**Comment by MicheleBertoli** [comment]
oh, sorry @leo. [fixed](https://github.com/MicheleBertoli/css-in-js/commit/b7a29feab25c4f0ff89d1e68424319789744519d).
thanks!

**Pull request merged**
