### PR TITLE
Add README section on Syntax Highlighting

### LINKED ISSUE #114: Syntax highlighting with atom & language-babel
Enable css syntax highlighting in atom when using language-babel package: gandm/language-babel#324

### PR DESCRIPTION
**Pull request by nikvm**
I thought this might close #114. Info taken from [here](https://github.com/gandm/language-babel/issues/324).

I'll be doing some research into how this could be accomplished in other editors.

### CODE REVIEW

**Comment by giuseppeg** [comment]
Awesome! I was thinking of adding a FAQ section at the bottom of README.md with a few `<summary>` blocks to answer the most common / related questions, like Next.js does https://github.com/zeit/next.js#faq .

To give you an idea every once somebody asks about this

```
Warning: Unknown prop `jsx` on <style> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in style (created by Unknown)
    in nav (created by Unknown)
    in Unknown (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by App)
    in App
```

which means that for some reason styled-jsx didn't run completely (eg. they are not using next@2.0.0-beta)

**Comment by nikvm** [comment]
Being blunt, I'm very much against FAQs. :gun:

It's a comfortable place to stuff in content that seemingly doesn't fit in anywhere else. In my opinion this only pushes the problem to the end user (who honestly doesn't know which questions are _frequently asked_). I'd rather think a little longer about where said content belongs and add appropriate sections if necessary. Note that __this is very much subjective__. But it's hard to get rid of a FAQ section once it's there [[1]](#user-content-next-faq).

The proposed _Syntax Highlighting_ section might seem superfluous at the moment due to it having only one entry. But I'm hoping it will grow over time as we find solutions for other editors. I also believe it's important enough to deserve it's own section.

As for your example: It might fit in a section _Common Pitfalls_ or better yet in the [Next.js](https://github.com/zeit/next.j) docs. So we can link to it when this type of error comes up.

In any case: No :heart: feelings. In the end it's not that big of a deal.

<a href="#user-content-next-faq" name="next-faq">[1]</a>: I'm working on [documentation improvements for Next.js](https://github.com/zeit/next.js/issues/1069). And I'm trying to get rid of the FAQ section for above reasons. Also I don't want to step on anybody's toes and would be happy to back away.

**Comment by nikvm** [comment]
To conclude: I wouldn't wait for more editors to make it to the list before merging. Personally I'm using [VS Code](https://code.visualstudio.com/) where it's currently not supported. If you'd rather  add it as a FAQ, feel free&mdash;or I can take care of that. :v:

I'd just like to see this documented somewhere and most&mdash;importantly&mdash;have the satisfaction of closing an issue. :metal:

**Comment by giuseppeg** [comment]
That's totally ok and makes sense. There are actual FAQ like the example I mentioned, but it is not a big deal we can add a paragraph for that later.

**Pull request merged**
