### PR TITLE
Update to Babel 7.x

### PR DESCRIPTION
**Pull request by benedyktdryl**
Hi, 

This is my very firs PR which includes Babel 7.x related updates. Please let me know if you will be interested in such contribution so I can make further updates in that matter.

### CODE REVIEW

**Comment by giuseppeg** [comment]
@benedyktdryl thanks! why not..

**Comment by benedyktdryl** [comment]
Thanks. Question: is there any chance this can be released under some beta tag? If yes, it will be easier to maintain changes in Next.js related PR:

https://github.com/zeit/next.js/pull/3428

**Comment by giuseppeg** [comment]
Oh sorry I forgot we had babel related `dependencies`. That is going to be an issue for the ones who don't use Babel 7 yet right? If that's the case maybe we can wait a bit or if Next.js needs styled-jsx to be on Babel 7 then we could release a separate, temporary version. Maybe dist-tag it with babel7

**Comment by benedyktdryl** [comment]
Indeed there will be an issue, an dist-tag is good idea, thanks.

**Comment by giuseppeg** [comment]
will reconsider this when Babel 6 is deprecated or we find a better way to guarantee backwards compatibility

**Pull request closed without merging**
