### PR TITLE
Fix typo explained in #509

### PR DESCRIPTION
**Pull request by ryanfitzer**
Fix typo explained in #509.

### CODE REVIEW

**Comment by giuseppeg** [comment]
to be honest I don't know exactly what is the difference between filename and sourceFileName:

https://github.com/zeit/styled-jsx/blob/1b3497517ec8743db3f236fe3191482578da121b/src/babel.js#L230-L238

I asked on the Babel slack community, let's wait for a reply.

The part you changed could be correct and the bug could be here https://github.com/zeit/styled-jsx/blob/1b3497517ec8743db3f236fe3191482578da121b/src/babel-external.js#L205-L209 (which is not computing and passing `filename`

**Comment by giuseppeg** [comment]
@ryanfitzer do you mind taking a look at these and see if `sourceFileName` is really what we need? I won't have time tonight/in the following days (maybe on Wed)

https://babeljs.io/docs/en/options#filename
https://babeljs.io/docs/en/options#filenamerelative
https://babeljs.io/docs/en/options#sourcefilename

**Comment by ryanfitzer** [comment]
@lluisrojass If you get time, can you take a look at this before Wednesday? I won't have time until Monday.

**Comment by giuseppeg** [comment]
closed in favor of #526

**Pull request closed without merging**
