### PR TITLE
Enable jsx tests

### PR DESCRIPTION
**Pull request by giuseppeg**
Enables tests for the babel plugin.
Also got rid of Gulp and fixed a number of bugs.

Relates to #1

### CODE REVIEW

**Comment by giuseppeg** [comment]
TODO: now that tests are enabled I need to figure out why the babel plugin is not doing its job. Any hint that could help me resolve this issue quickly would be appreciated.

**Comment by giuseppeg** [comment]
@rauchg @leo tests were disabled and never ran on build. There were a number of bugs in the Babel plugin that I fixed. Please review :)

**Comment by nkzawa** [comment]
We fixed tests on the master branch. Can you merge it and run tests ?

**Comment by nkzawa** [comment]
Or maybe we should just close the PR ?

**Comment by giuseppeg** [comment]
@nkzawa cool, let me know if you want me to put together new branch with the gulp removal, the removal of the nested `if`s and the comments I added to the code.

**Pull request closed without merging**
