### PR TITLE
add --save-dev [skip ci]

### PR DESCRIPTION
**Pull request by hzoo**
We usually add plugins as devDeps

### CODE REVIEW

**Comment by leo** [comment]
Woopsie! You're right, of course. Thanks! ❤️

**Comment by nkzawa** [comment]
I think some files are for runtime, so it has to be `--save` ?

**Comment by leo** [comment]
The client, yep. Fixing!

**Comment by hzoo** [comment]
Oh you mean `import _jsxStyleInject from 'styled-jsx/inject'`

**Comment by hzoo** [comment]
It was just weird to me about babel-core being a dep ref https://github.com/zeit/styled-jsx/pull/7

**Pull request merged**
