### PR TITLE
Show how to select children of global element

### PR DESCRIPTION
**Pull request by timneutkens**

### CODE REVIEW

**Comment by giuseppeg** [comment]
doesn't `div :global(.react-select .some-child-of-react-select) {}` work?

**Comment by timneutkens** [comment]
`div :global(.react-select .some-child-of-react-select)` compiles down to `div[12345] .react-select .some-child-of-react-select)` Notice the ending `)`. I'm not sure if this is an issue, or by intent :smile:

**Comment by giuseppeg** [comment]
oh definitely a bug! Thanks I keep saying that we should rewrite the global part :)

**Comment by rauchg** [comment]
This is a good workaround until we make a permanent fix. Thanks @timneutkens

**Pull request merged**
